version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: codyssey
      POSTGRES_PASSWORD: codyssey
      POSTGRES_DB: codyssey
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-00-00Z
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  go-backend:
    build: ../backend
    environment:
      GO_BACKEND_PORT: 8080
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq
      - minio

  py-backend:
    build: ../python
    environment:
      PY_BACKEND_PORT: 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - rabbitmq
      - minio

  frontend:
    build: ../frontend
    command: ["npm","run","dev"]
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_GO_API: http://localhost:8080
      NEXT_PUBLIC_PY_API: http://localhost:8000
    depends_on:
      - go-backend
      - py-backend

volumes:
  pg_data:
  minio_data:
