version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: codyssey-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-codyssey}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-codyssey}
      POSTGRES_DB: ${POSTGRES_DB:-codyssey}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: codyssey-rabbitmq
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MGMT_PORT:-15672}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}

  minio:
    image: quay.io/minio/minio:RELEASE.2024-09-22T00-00-00Z
    container_name: codyssey-minio
    command: server /data --console-address :9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minio}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minio123}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio_data:/data

volumes:
  pg_data:
  minio_data:
