import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/src/app/providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Web Vitals 上报：Next.js 会在客户端调用此导出函数
export function reportWebVitals(metric: any) {
  try {
    if (process.env.NEXT_PUBLIC_LOG_WEB_VITALS === 'true') {
      // 简单输出到控制台（可扩展 POST 到后端 /metrics 或 /vitals）
      // metric: { id, name, startTime, value, label }
      console.info('[WebVital]', metric.name, metric.value, metric);
    }
    // TODO: 如果需要后端聚合，可使用 navigator.sendBeacon 或 fetch
    // if (typeof navigator !== 'undefined' && navigator.sendBeacon) {
    //   const body = JSON.stringify(metric);
    //   navigator.sendBeacon('/api/vitals', body);
    // }
  } catch (e) {
    // 静默失败
  }
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-background text-foreground` }>
        <AppProviders>
          {children}
        </AppProviders>
      </body>
    </html>
  );
}
